services:
  ##################################
  # Public Worker
  ##################################
  worker:
    image: worker:latest
    hostname: worker
    build: .
    ports:
      - "514:514"
    expose:
      - "514"
    command:
      - --appID
      - "[Enter your appID here.]"    